name: Increment counter daily

on:
  schedule:
    # Runs at 00:05 UTC every day – adjust as you like
    - cron: '5 0 * * *'
  workflow_dispatch:          # manual trigger if needed

env:
  FILE: counter.txt           # path to the counter file

jobs:
  increment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # repo-scoped token

      - name: workflow-runner
        id: bump
        run: |
          set -euo pipefail
          current=$(cat "$FILE" | tr -d '\r\n' || echo 0)

          if ! [[ "$current" =~ ^[0-9]+$ ]]; then
            echo "File '$FILE' does not contain a plain integer." >&2
            exit 1
          fi

          next=$((current + 1))
          echo "$next" > "$FILE"

          # expose the new value as an output for later steps
          echo "next=$next" >> "$GITHUB_OUTPUT"

      
      - name: Set commit message
        run: |
          ts=$(date -u '+%Y-%m-%d %H:%M:%S')
          echo "COMMIT_MESSAGE=Update number: $ts" >> "$GITHUB_ENV"

      
      - name: Commit and push if changed
        run: |
          if [[ -n "$(git status --porcelain "$FILE")" ]]; then
            git config --global user.name  "seltygg"
            git config --global user.email "sankalpsikchi@arizona.edu"

            git add "$FILE"
            git commit -m "$COMMIT_MESSAGE"
            git push
          else
            echo "No change to commit."
          fi
